name: 'Dependency tree diff for Gradle'
description: "Dependency tree diff generates human readable dependency diff between 2 commits, using Jake Wharton's dependency-tree-diff tool"
inputs:
  configuration:
    description: 'Selected configuration'
    required: false
    default: 'releaseRuntimeClasspath'
  project:
    description: 'Project'
    required: false
    default: 'app'
  build-root-directory:
    description: 'Build root directory'
    required: false
    default: .
  lib-version:
    description: 'Dependency diff library version'
    required: true
    default: '1.1.0'
outputs:
  text-diff:
    description: "Dependency diff"
    value: ${{ steps.diff-generator.outputs.text-diff }}
runs:
  using: 'composite'
  steps:
    - id: diff-generator
      env:
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_CONFIGURATION: ${{ inputs.configuration }}
        INPUT_BASEREF: ${{ github.base_ref }}
        INPUT_BUILD_ROOT_DIR: ${{ inputs.build-root-directory }}
        INPUT_VERSION: ${{ inputs.lib-version }}
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
