on:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Run dependency diff action
    steps:
      - uses: actions/checkout@v2
      - id: dependency-diff
        uses: ./
        with:
          configuration: runtimeClasspath
          build-root-directory: testproject
          project: ""
      - run: echo ${{ steps.dependency-diff.outputs.text-diff }}
        shell: bash
