on:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Run dependency diff action
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: testproject
          arguments: dependencies

      - id: dependency-diff
        uses: ./
        with:
          configuration: runtimeClasspath
          build-root-directory: testproject
          project: ""

      - run: echo '${{ steps.dependency-diff.outputs.text-diff }}'
        shell: bash
